#colors
BLACK = (0,0,0)
WHITE = (255,255,255)

SCALE = 32

HEIGHT = 640
WIDTH = 480

MAP_TILE_GRASS = "G"
MAP_TILE_WATER = "W"
MAP_TILE_ROAD = "R"
MAP_TILE_LONG_GRASS = "L"
MAP_TILE_TREE = "T"

IMPASSABLE = {MAP_TILE_TREE,MAP_TILE_WATER}